In [1]:
def ReadOImgs(root):
    import os
    datalist=[]
    for path, subdirs, files in os.walk(root):
        for name in files:
            if name.endswith('.png') or name.endswith('.JPEG'):
                imgpath=os.path.join(path, name)
                datalist.append(imgpath)
    return datalist

cars=ReadOImgs("./data/vehicles")
notcars=ReadOImgs("./data/non-vehicles")

In [3]:
import matplotlib.image as mpimg
car1 = mpimg.imread(cars[0])
notcar1=mpimg.imread(notcars[0])

In [11]:
print(type(car1))
print(car1)

<class 'numpy.ndarray'>
[[[ 0.61176473  0.65882355  0.63921571]
  [ 0.61176473  0.65882355  0.63921571]
  [ 0.61176473  0.65490198  0.63529414]
  ..., 
  [ 0.39215687  0.43921569  0.35294119]
  [ 0.40000001  0.44313726  0.35686275]
  [ 0.40392157  0.44313726  0.35686275]]

 [[ 0.61176473  0.65882355  0.63921571]
  [ 0.61176473  0.65882355  0.63921571]
  [ 0.61176473  0.65490198  0.63529414]
  ..., 
  [ 0.39215687  0.43921569  0.35294119]
  [ 0.40000001  0.44313726  0.35686275]
  [ 0.40392157  0.44313726  0.35686275]]

 [[ 0.61176473  0.65490198  0.63137257]
  [ 0.61176473  0.65490198  0.63137257]
  [ 0.61176473  0.65098041  0.627451  ]
  ..., 
  [ 0.39215687  0.44313726  0.35294119]
  [ 0.40000001  0.44705883  0.36078432]
  [ 0.40392157  0.44705883  0.36078432]]

 ..., 
 [[ 0.48235294  0.50196081  0.4509804 ]
  [ 0.48235294  0.50196081  0.4509804 ]
  [ 0.48235294  0.49803922  0.44705883]
  ..., 
  [ 0.62352943  0.62352943  0.5529412 ]
  [ 0.62352943  0.62352943  0.54901963]
  [ 0.62352

In [7]:
testimage = mpimg.imread('./test_images/test1.jpg')
print(testimage)

[[[254 233 216]
  [245 238 232]
  [196 205 212]
  ..., 
  [ 16  35  52]
  [ 20  37  53]
  [ 32  48  63]]

 [[245 238 232]
  [188 193 197]
  [137 158 175]
  ..., 
  [ 74 108 135]
  [ 47  77 103]
  [  4  34  60]]

 [[193 202 209]
  [134 157 173]
  [115 154 183]
  ..., 
  [ 95 144 184]
  [ 89 137 177]
  [ 52  97 136]]

 ..., 
 [[141 131 129]
  [132 121 119]
  [114 100  97]
  ..., 
  [ 99  80  74]
  [ 99  80  74]
  [113  94  88]]

 [[164 154 152]
  [133 122 120]
  [120 106 103]
  ..., 
  [107  88  82]
  [109  90  84]
  [111  92  86]]

 [[189 179 177]
  [135 125 123]
  [128 117 113]
  ..., 
  [ 97  78  72]
  [ 95  76  70]
  [ 73  54  48]]]


In [8]:
print(notcar1)

[[[109 142 175]
  [115 149 184]
  [113 151 188]
  ..., 
  [107 150 193]
  [108 151 194]
  [108 151 194]]

 [[108 143 175]
  [115 149 184]
  [113 151 188]
  ..., 
  [107 150 193]
  [108 151 194]
  [108 151 194]]

 [[107 142 174]
  [115 149 184]
  [113 151 188]
  ..., 
  [108 151 194]
  [108 151 194]
  [108 151 194]]

 ..., 
 [[108 126 148]
  [104 125 146]
  [109 131 154]
  ..., 
  [ 85  84  89]
  [ 87  85  88]
  [ 84  82  85]]

 [[115 131 154]
  [123 141 163]
  [127 145 167]
  ..., 
  [108 106 111]
  [123 121 126]
  [121 119 122]]

 [[122 136 162]
  [138 154 177]
  [110 128 150]
  ..., 
  [ 97  95  98]
  [ 90  88  93]
  [ 85  83  88]]]


In [12]:
import numpy as np
notcar1 = notcar1.astype(np.float32)/255
print(type(notcar1))

<class 'numpy.ndarray'>
